# Generated by Django 4.2.3 on 2024-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_channel_id_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='channel_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
