# Generated by Django 4.2.3 on 2024-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reach',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriber',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='videos',
            field=models.IntegerField(blank=True, default=0, max_length=200),
        ),
    ]
