# Generated by Django 4.2.3 on 2024-08-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile_reach_profile_subscriber_profile_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='videos',
        ),
    ]
