# Generated by Django 4.2.3 on 2024-08-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_profile_channel_id_remove_profile_reach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='channel_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
